# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user',
            new_name='contestant',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='contestant',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
