# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170818_2024'),
        ('inbox', '0005_auto_20170902_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='review',
        ),
        migrations.AddField(
            model_name='conversation',
            name='review',
            field=models.ManyToManyField(related_name='review', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contestant',
            field=models.ManyToManyField(related_name='contestant', to='profiles.Profile'),
        ),
    ]
