# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_auto_20170903_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='review', to='profiles.Profile'),
        ),
    ]
