# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0007_auto_20170907_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='notice',
            field=models.ManyToManyField(blank=True, to='things.Notice'),
        ),
    ]
