# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 02:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='iconos/icono.png', upload_to='iconos')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/no-avatar.png', upload_to='avatars')),
                ('birth_date', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('biography', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, max_length=40)),
                ('profession', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=40)),
                ('avialability', models.CharField(blank=True, max_length=40)),
                ('icono', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Icon')),
                ('location', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.Place')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='profiles.Profile'),
        ),
    ]
