# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170325_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/no-avatar.png', upload_to='avatars'),
        ),
    ]
