# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170327_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='profiles.Place'),
        ),
    ]
