# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='place',
        ),
        migrations.AddField(
            model_name='profile',
            name='biografy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.Place'),
        ),
    ]
