# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20170328_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biografy',
            new_name='biography',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
