# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20170405_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(b'F', b'Femenino'), (b'M', b'Masculino')], default=b'M', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='profiles.Place'),
        ),
    ]
