# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_merge_20170405_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
