# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20170517_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avialability',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
