# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='Category/no.image.png', upload_to=profiles.models.File.generatePath),
        ),
    ]
