# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20170406_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=28),
        ),
    ]
