# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
