# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('optionTrade', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Notice'),
        ),
    ]
