# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hexa', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('money', models.BooleanField(default=True)),
                ('kind', models.IntegerField(default=1)),
                ('visibility', models.BooleanField(default=True)),
                ('urgency', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.Notice')),
                ('profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('N', 'Nuevo'), ('U', 'Usado'), ('E', 'Por Encargo'), ('B', 'Restaurado'), ('R', 'Reparado'), ('M', 'Mejorado'), ('C', 'Cualquiera')], default='N', max_length=1)),
                ('delivery', models.CharField(choices=[('E', 'Yo mismo lo entrego'), ('C', 'Convenio'), ('R', 'Redzza service')], default='C', max_length=1)),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='things.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(blank=True)),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='things.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Notice')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Notice'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Notice'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='things.Product'),
        ),
        migrations.AddField(
            model_name='citynotice',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Notice'),
        ),
    ]
