# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=profiles.models.File.generatePath),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=profiles.models.File.generatePath),
        ),
    ]
