# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('size', models.IntegerField(blank=True)),
                ('state', models.CharField(choices=[('Nuevo', 'N'), ('Usado', 'U'), ('Reparado', 'R')], default='Nuevo', max_length=8)),
                ('measure', models.CommaSeparatedIntegerField(blank=True, max_length=20)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Color')),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='things.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True)),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='things.Notice')),
            ],
        ),
    ]
