# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170818_2024'),
        ('things', '0002_auto_20170818_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.Place'),
        ),
    ]
