# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_product_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='things.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('N', 'Nuevo'), ('U', 'Usado'), ('R', 'Reparado')], default='Nuevo', max_length=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
