# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_notice_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
