# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20170417_1656'),
        ('categories', '0004_auto_20170407_0101'),
        ('things', '0004_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CityNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Place')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AddField(
            model_name='notice',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='citynotice',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Notice'),
        ),
        migrations.AddField(
            model_name='categorytrade',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Notice'),
        ),
    ]
