# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_auto_20170508_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='hexa',
        ),
    ]
