# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0007_auto_20170517_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='optionTrade',
        ),
    ]
