# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 22:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0009_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
