# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0010_auto_20170531_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='kind',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('N', 'Nuevo'), ('U', 'Usado'), ('E', 'Por Encargo'), ('B', 'Restaurado'), ('R', 'Renovado'), ('C', 'Cualquiera')], default='Nuevo', max_length=1),
        ),
    ]
