# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0011_auto_20170601_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
