# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0013_auto_20170718_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.CharField(choices=[('E', 'Yo mismo lo entrego'), ('C', 'Convenio'), ('R', 'Redzza service')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('N', 'Nuevo'), ('U', 'Usado'), ('E', 'Por Encargo'), ('B', 'Restaurado'), ('R', 'Renovado'), ('C', 'Cualquiera')], default='N', max_length=1),
        ),
    ]
