# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0014_auto_20170718_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='notice',
            name='money',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.Notice'),
        ),
        migrations.AddField(
            model_name='notice',
            name='urgency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('N', 'Nuevo'), ('U', 'Usado'), ('E', 'Por Encargo'), ('B', 'Restaurado'), ('R', 'Reparado'), ('M', 'Mejorado'), ('C', 'Cualquiera')], default='N', max_length=1),
        ),
    ]
