# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0015_auto_20170726_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
