# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0016_remove_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
    ]
